### ISSUE TITLE
katana is borked

### ISSUE THREAD

**Issue by xull** [bluegill/katana#60]
plz fix

**Comment by mariogarridopt** [comment]
Looks like this repo is no longer active...

**Comment by berot3** [comment]
Can someone archive it then please?

**Comment by mariogarridopt** [comment]
Since the Owner is not responding we cant archive it.
I created a project inspired by Katana that works similarly.
Some features are missing like link shortening and so, but the development is ongoing. If someone wanna contribute to help that would be great too. Check it out: https://github.com/mariogarridopt/Saphira/releases/tag/v1.0.0
